parameters:
#    qualium_in_fact_inventario.example.class: Qualium\InFact\InventarioBundle\Example

services:
#    qualium_in_fact_inventario.example:
#        class: %qualium_in_fact_inventario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
