<?php

namespace Qualium\InFact\AmalgamaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosRepository extends EntityRepository
{
}
