<?php

namespace Qualium\InFact\AmalgamaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransaccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionesRepository extends EntityRepository
{
}
