qualium_in_fact_amalgama_inicio:
    pattern:  /
    defaults: { _controller: QualiumInFactAmalgamaBundle:Default:index }

inventario:
    pattern: /herramienta/inventario
    defaults: { _controller: QualiumInFactAmalgamaBundle:Default:inventarioIndex }
    
ajax_producto_id:
    pattern: /ajax/producto/id/{idProducto}
    defaults: { _controller: QualiumInFactAmalgamaBundle:Ajax:obtenerProductoPorId, idProducto: 0 }
    requirements:
        idProducto: \d+

ajax_producto_codigobarra:
    pattern: /ajax/producto/codigobarra/{codigoBarra}
    defaults: { _controller: QualiumInFactAmalgamaBundle:Ajax:obtenerProductoPorCodigoBarra, codigoBarra: 0 }
    requirements:
        codigoBarra: \d+


QualiumInFactAmalgamaBundle_admin_inventario:
        resource: "@QualiumInFactAmalgamaBundle/Resources/config/routing/inventario.yml"
        prefix:   /admin/inventario
