qualium_in_fact_amalgama_inicio:
    pattern:  /
    defaults: { _controller: QualiumInFactAmalgamaBundle:Default:index }

inventario:
    pattern: /inventario/herramienta/{operacion}
    defaults: { _controller: QualiumInFactAmalgamaBundle:Default:inventarioIndex, operacion : 'salida' }
    
ajax_producto_id:
    pattern: /inventario/ajax/producto/id/{idProducto}
    defaults: { _controller: QualiumInFactAmalgamaBundle:AjaxInventario:obtenerProductoPorId, idProducto: 0 }
    requirements:
        idProducto: \d+

ajax_inventario_procesar:
    pattern: /inventario/ajax/procesar
    defaults: { _controller: QualiumInFactAmalgamaBundle:AjaxInventario:procesarInventarioVirtual }


ajax_producto_codigobarra:
    pattern: /inventario/ajax/producto/codigobarra/{operacion}/{codigoBarra}
    defaults: { _controller: QualiumInFactAmalgamaBundle:AjaxInventario:obtenerProductoPorCodigoBarra, operacion: 'salida', codigoBarra: 0 }
    requirements:
        codigoBarra: \d+
        
ajax_eliminarInventarioVirtual:
    pattern: /inventario/ajax/eliminarInventarioVirtual
    defaults: { _controller: QualiumInFactAmalgamaBundle:AjaxInventario:eliminarInventarioVirtual }

ajax_cargarInventarioVirtual:
    pattern: /inventario/ajax/cargarInventarioVirtual
    defaults: { _controller: QualiumInFactAmalgamaBundle:AjaxInventario:cargarInventarioVirtual }

QualiumInFactAmalgamaBundle_admin_inventario:
        resource: "@QualiumInFactAmalgamaBundle/Resources/config/routing/inventario.yml"
        prefix:   /admin/inventario

QualiumInFactAmalgamaBundle_admin_inventario_dependencia:
        resource: "@QualiumInFactAmalgamaBundle/Resources/config/routing/inventariodependencia.yml"
        prefix:   /admin/inventario/dependencia
