parameters:
#    qualium_in_fact_amalgama.example.class: Qualium\InFact\AmalgamaBundle\Example

services:
#    qualium_in_fact_amalgama.example:
#        class: %qualium_in_fact_amalgama.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
