Qualium\InFact\AmalgamaBundle\Entity\Estados:
    type: entity
    table: null
    repositoryClass: Qualium\InFact\AmalgamaBundle\Entity\EstadosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ftEvento:
            type: datetime
        idUsuario:
            type: integer
        nota:
            type: string
            length: 255
        flagImportante:
            type: boolean
            
    manyToOne:
        idTransacciones:
            targetEntity: Transacciones
            joinColumn:
              nullable: true
              name: idTransacciones
              referencedColumnName: id
              onDelete: RESTRICT
        idInventario:
            targetEntity: Inventario
            joinColumn:
              nullable: false
              name: idInventario
              referencedColumnName: id
              onDelete: RESTRICT

    lifecycleCallbacks: {  }
