Qualium\InFact\AmalgamaBundle\Entity\InventarioDependencia:
    type: entity
    table: null
    repositoryClass: Qualium\InFact\AmalgamaBundle\Entity\InventarioDependenciaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razon:
            type: string
            length: 255
    manyToOne:
        idInventario:
            targetEntity: Inventario
            joinColumn:
              nullable: false
              referencedColumnName: id
              onDelete: RESTRICT
        idInventarioRequerido:
            targetEntity: Inventario
            joinColumn:
              nullable: false
              referencedColumnName: id
              onDelete: RESTRICT
    
    lifecycleCallbacks: {  }
