Qualium\InFact\AmalgamaBundle\Entity\Inventario:
    type: entity
    table: null
    indexes:
        flagRestriccion_ix:
          columns: [ flagRestriccion ]
        flagDescontinuado_ix:
          columns: [ flagRestriccion ]
        
    repositoryClass: Qualium\InFact\AmalgamaBundle\Entity\InventarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigoBarra:
            type: string
            length: 255
            unique: true
        nombre:
            type: string
            length: 255
        descripcion:
            type: string
            length: 255
        fechaCompra:
            type: date
        flagRestriccion:
            type: boolean
            nullable: true
        flagDescontinuado:
            type: boolean
            nullable: true
        cantidadDisponible:
            type: integer
            notnull: true;
            
    manyToOne:
        idPropietario:
            targetEntity: User
            joinColumn:
              nullable: false
              name: idPropietario
              referencedColumnName: id
              onDelete: RESTRICT

    lifecycleCallbacks: {  }
